# Generated by Django 4.1.1 on 2022-11-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourstory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=25, null=True)),
                ('text', models.CharField(max_length=255, null=True)),
                ('file', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'calendars',
            },
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
