# Generated by Django 4.1.1 on 2022-11-25 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ourstory', '0002_calendar_delete_answer_delete_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendar',
            old_name='file',
            new_name='image',
        ),
    ]
