# Generated by Django 4.1.1 on 2022-11-26 02:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourstory', '0003_rename_file_calendar_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='date',
        ),
        migrations.AddField(
            model_name='calendar',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='calendar',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
